### PR TITLE
The coordinates always return to the center point of the map when editing a record and showMarker is activated

### PR DESCRIPTION
**Pull request by binsarjr**
Screenshot 2024-12-02 at 03 39 29

I tried to track one by one where the problem was, the problem was, when editing and showMarker and clickable were activated. which will run the function `setCoordinates -> updateMarker -> updateLocation`

Here the coordinates have been set and saved to the latest state by running the `setCoordinates` function

but the problem is every time this `setCoordinates` is executed, also call `updateLocation` which apparently `updateLocation` will also update the coordinates with the center point

see `setCoordinates` always call `updateMarker`

https://github.com/dotswan/filament-map-picker/blob/285158a99a09f3dc92c87fdf1bf5231e4396575a/resources/js/index.js#L278-L291

and `updateMarker` also call `updateLocation` when showMarker is true, this function will take the coordinates of the center point of the map

https://github.com/dotswan/filament-map-picker/blob/285158a99a09f3dc92c87fdf1bf5231e4396575a/resources/js/index.js#L365-L371

so that every time the map picker moves, the coordinates will always return to the center point

this is function `updateLocation`:
https://github.com/dotswan/filament-map-picker/blob/285158a99a09f3dc92c87fdf1bf5231e4396575a/resources/js/index.js#L233-L248

### CODE REVIEW

**Comment by binsarjr** [comment]
Related #56

**Comment by artumi-richard** [comment]
I've got an incoming pull request that deals with this also, but in a different way. I'll get that up shortly and then I'll compare with this one.

**Comment by artumi-richard** [comment]
@binsarjr  I'd love to hear what you think of my pull request #59

**Comment by binsarjr** [comment]
hello @artumi-richard  sorry for this late reply. from the code that I have myself it is only temporary code and I realize that the logic is confusing and I have also seen your solution, I think it is better with code that is also easier to read.

**Comment by artumi-richard** [comment]
@binsarjr  Thanks! That's probably the one to merge then.

**Comment by binsarjr** [comment]
Yes, thank @artumi-richard , we'll use your [PR](#59 ), I'll close mine

**Comment by mohaphez** [comment]
Hello @binsarjr and @artumi-richard,

Thank you both for your efforts and active participation, it’s greatly appreciated!

The new PR will be published soon, and the updated version will be presented shortly.

**Pull request closed without merging**
